package com.rjtech.common.utils;

public enum ModuleCodesPrefixes {
    EMP_ATTENDENCE_PREFIX("EAR"), PLANT_ATTENDENCE_PREFIX("PAR"), TIME_SHEET_PREFIX("TS"), WORK_DIARY_PREFIX("WD"),
    EMP_REG_PREFIX("ER"), PLANT_REG_PREFIX("PR"), MATERIAL_REG_PREFIX("MR"), PRE_CONTRACT_PREFIX("PRE"),
    PRE_CONTRACT_SCH_PREFIX("SCH"), PRE_CONTRACT_MAN_SCH_PREFIX("MAN-SCH"), PRE_CONTRACT_PLANT_SCH_PREFIX("PLANT-SCH"),
    PRE_CONTRACT_MATERIAL_SCH_PREFIX("MAT-SCH"), PRE_CONTRACT_SERVICE_SCH_PREFIX("SERV-SCH"),
    PRE_CONTRACT_SOW_SCH_PREFIX("SOW-SCH"), PRE_CONTRACT_CMP_DOC_PREFIX("RFW-SCH"), PRE_CONTRACT_DOC_PREFIX("PRE-DOC"),
    PROJ_DOC_PREFIX("DOC"), PROCURE_NOTIFICATION("PRN"), RFQ_CODE("RFQ"), PURCHASE_ORDER("PO"), REQUEST_PREFIX("REQ"),
    APPROVE_PREFIX("APPR"), NOTIFICATION_PREFIX("NOTIFY"), PROJ_SCHEDULE_PREFIX("SCH"), PRE_CONTRACT_REQ_PREFIX("PRR"),
    PRE_CONTRACT_APPR_PREFIX("PRA"), MEDICAL_DOCUMENT("MD"), PROJECT_DOCKET("PD"), PROJ_INVOICE_PREFIX("INV"),QUAL_PREFIX("QUAL"),
    SOE_PREFIX("SOE");

    private final String desc;

    private ModuleCodesPrefixes(String desc) {
        this.desc = desc;
    }

    public String getDesc() {
        return desc;
    }

}
