package com.rjtech.common.utils;

public enum ModuleCodes {
    PROCUREMENT(1, "PROCURMT"), ATTENDENCE(2, "ATNDNCERCRDS"), WORK_DAIRY(3, "WRKDIRY"), TIME_SHEET(4, "TIMSHET"),
    EMPLOYEE_TRANSFER(5, "EMPTRSFR"), PLANT_TRANSFER(6, "PLANTTRSFR"), MATERIAL_TRANSFER(7, "MATRLTRSFR"),
    GENERAL_VALUES(7, "GNRLVLU"), PLANT_REQ_FOR_TRANS(7, "PLANTREQTRANS"), EMP_REQ_FOR_TRANS(7, "EMPREQTRANS"),
    MATERIAL_REQ_FOR_TRANS(7, "MATERIALREQTRANS"), EMP_NOTIFICATION(8, "EMP_NOTIFICATION"),
    PLANT_NOTIFICATION(9, "PLANT_NOTIFICATION"), TIMESHEET_NOTIFICATION(10, "TIME_SHEET_NOTIFICATION"),
    WORK_DIARY_NOTIFICATION(11, "WORK_DIARY_NOTIFICATION"), EMP_TRANS_NOTIFICATION(12, "EMP_TRANS_NOTIFICATION"),
    PLANT_TRANS_NOTIFICATION(13, "PLANT_TRANS_NOTIFICATION"),
    MATERIAL_TRANS_NOTIFICATION(14, "MATERIAL_TRANS_NOTIFICATION"), PROCUREDOC(15, "PROCUREDOC"),
    PRECONTRACT_SCH_ITEM(16, "PRECONTRACT_SCH_ITEM"), PROCURE_CMP_DOC(17, "PROCURE_CMP_DOC"),
    PROJ_DOCUMENT(18, "PROJ_DOCUMENT"), DOCUMENT(19, "DOCMTT"), EMP_LEAVE_REQUEST(20, "EMP_LEAVE_REQUEST"),
    PURCHASE_ORDER(21, "PURCHASE_ORDER"), MATERIAL_PROJ_DOCKET(22, "MATERIAL_PROJ_DOCKET"),
    MATERIAL_PROJ_DOCKET_NOTIFICATION(23, "MATERIAL_PROJ_DOCKET_NOTIFICATION"),
    INTERNALREQAPPOVAL(24, "INTERNALREQAPPOVAL"), EXTERNALREQAPPOVAL(25, "EXTERNALREQAPPOVAL"),
    PROJ_SCHEDULE(26, "PROJ_SCHEDULE"), PRECONTRACT_REQ_APPR(27, "PRECONTRACT_REQ_APPR"),
    MEDICAL_DOCUMENT(28, "MEDICAL_DOCUMENT"), PROJ_INVOICE(29, "INVOICE");

    private final Integer value;
    private final String desc;

    private ModuleCodes(Integer value, String desc) {
        this.value = value;
        this.desc = desc;
    }

    public Integer getValue() {
        return value;
    }

    public String getDesc() {
        return desc;
    }

    public static String getDescValue(Integer value) {
        for (ModuleCodes workFlowStatus : ModuleCodes.values()) {
            if (workFlowStatus.getValue().equals(value)) {
                return workFlowStatus.getDesc();
            }
        }
        return null;
    }

}
