server:
    port: 8080

spring:
    jpa:
        openInView: false
        show_sql: true
        generate-ddl: false
        hibernate:
            ddl-auto: none
            naming-strategy: org.hibernate.cfg.EJB3NamingStrategy
        properties:
            hibernate.cache.use_second_level_cache: false
            hibernate.cache.use_query_cache: false
            hibernate.generate_statistics: true

    mail:
        baseUrl: http://192.168.1.15:9280

    thymeleaf:
        mode: XHTML
        cache: false
        viewNames: error

metrics:
    jmx.enabled: true
    graphite:
        enabled: false
        host: localhost
        port: 2003
        prefix: pot

potep:       
    centralLibUrl: http://183.82.102.74:9280/centlib
    projectLibUrl: http://183.82.102.74:9280/projlib
    adminUrl: http://183.82.102.74:9280/admin
    timeManagementUrl: http://183.82.102.74:9280/timemanagement
    projsettingsUrl: http://183.82.102.74:9280/projsettings
    procurementUrl: http://183.82.102.74:9280/procurement
    registerUrl: http://183.82.102.74:9280/register
    financeUrl: http://183.82.102.74:9280/finance
    notificationUrl: http://183.82.102.74:9280/notification
