server:
    port: 8080

spring:
    jpa:
        openInView: false
        show_sql: true
        generate-ddl: false
        hibernate:
            ddl-auto: none
            naming-strategy: org.hibernate.cfg.EJB3NamingStrategy
        properties:
            hibernate.cache.use_second_level_cache: false
            hibernate.cache.use_query_cache: false
            hibernate.generate_statistics: true

    mail:
        baseUrl: http://ec2-3-16-92-110.us-east-2.compute.amazonaws.com:8080

    thymeleaf:
        mode: XHTML
        cache: false
        viewNames: error
    http:
        multipart:
            max-request-size: 5MB
            max-file-size: 5MB

metrics:
    jmx.enabled: true
    graphite:
        enabled: false
        host: localhost
        port: 2003
        prefix: pot

potep:       
    centralLibUrl: http://192.168.1.15:9280/centlib
    projectLibUrl: http://192.168.1.15:9280/projlib
    adminUrl: http://192.168.1.15:9280/admin
    timeManagementUrl: http://192.168.1.15:9280/timemanagement
    projsettingsUrl: http://192.168.1.15:9280/projsettings
    procurementUrl: http://192.168.1.15:9280/procurement
    registerUrl: http://192.168.1.15:9280/register
    financeUrl: http://192.168.1.15:9280/finance
    notificationUrl: http://192.168.1.15:9280/notification
    