INSERT INTO proj_leave_type_mstr 
(PJL_LVM_CODE,PJL_LVM_NAME, PJL_PRIOR_APPROVAL, PJL_MEDICAL_FORM, PJL_EVIDENCE_FORM, PJL_MAX_ALLOW_YEAR, PJL_MAX_ALLOW_EVENT, PJL_STATUS) VALUES
('P', 'Present', 0, 0, 0, 0, 0, 1);

INSERT INTO proj_leave_type_mstr 
(PJL_LVM_CODE,PJL_LVM_NAME, PJL_PRIOR_APPROVAL, PJL_MEDICAL_FORM, PJL_EVIDENCE_FORM, PJL_MAX_ALLOW_YEAR, PJL_MAX_ALLOW_EVENT, PJL_STATUS) VALUES
('AB', 'Absent', 0, 0, 0, 0, 0, 1);

INSERT INTO proj_leave_type_mstr 
(PJL_LVM_CODE,PJL_LVM_NAME, PJL_PRIOR_APPROVAL, PJL_MEDICAL_FORM, PJL_EVIDENCE_FORM, PJL_MAX_ALLOW_YEAR, PJL_MAX_ALLOW_EVENT, PJL_STATUS) VALUES
('PH', 'Public Holiday', 0, 0, 0, 0, 0, 1);

INSERT INTO proj_leave_type_mstr 
(PJL_LVM_CODE,PJL_LVM_NAME, PJL_PRIOR_APPROVAL, PJL_MEDICAL_FORM, PJL_EVIDENCE_FORM, PJL_MAX_ALLOW_YEAR, PJL_MAX_ALLOW_EVENT, PJL_STATUS) VALUES
('AL', 'Annual Leave', 1, 0, 0, 20, 20, 1);

INSERT INTO proj_leave_type_mstr 
(PJL_LVM_CODE,PJL_LVM_NAME, PJL_PRIOR_APPROVAL, PJL_MEDICAL_FORM, PJL_EVIDENCE_FORM, PJL_MAX_ALLOW_YEAR, PJL_MAX_ALLOW_EVENT, PJL_STATUS) VALUES
('LSL', 'Long Service Leave', 1, 0, 0, 4, 20, 1);

INSERT INTO proj_leave_type_mstr 
(PJL_LVM_CODE,PJL_LVM_NAME, PJL_PRIOR_APPROVAL, PJL_MEDICAL_FORM, PJL_EVIDENCE_FORM, PJL_MAX_ALLOW_YEAR, PJL_MAX_ALLOW_EVENT, PJL_STATUS) VALUES
('SL', 'Sick Leave', 0, 1, 1, 10, 10, 1);

INSERT INTO proj_leave_type_mstr 
(PJL_LVM_CODE,PJL_LVM_NAME, PJL_PRIOR_APPROVAL, PJL_MEDICAL_FORM, PJL_EVIDENCE_FORM, PJL_MAX_ALLOW_YEAR, PJL_MAX_ALLOW_EVENT, PJL_STATUS) VALUES
('ML', 'Maternity / Parental  Leave', 1, 1, 0, 90, 90, 1);

INSERT INTO proj_leave_type_mstr 
(PJL_LVM_CODE,PJL_LVM_NAME, PJL_PRIOR_APPROVAL, PJL_MEDICAL_FORM, PJL_EVIDENCE_FORM, PJL_MAX_ALLOW_YEAR, PJL_MAX_ALLOW_EVENT, PJL_STATUS) VALUES
('CBL', 'Compassionate & Bereavement Leave', 0, 0, 1, 2, 2, 1);

INSERT INTO proj_leave_type_mstr 
(PJL_LVM_CODE,PJL_LVM_NAME, PJL_PRIOR_APPROVAL, PJL_MEDICAL_FORM, PJL_EVIDENCE_FORM, PJL_MAX_ALLOW_YEAR, PJL_MAX_ALLOW_EVENT, PJL_STATUS) VALUES
('CSL', 'Community Service Leave', 0, 0, 1, 10, 10, 1);

INSERT INTO proj_leave_type_mstr 
(PJL_LVM_CODE,PJL_LVM_NAME, PJL_PRIOR_APPROVAL, PJL_MEDICAL_FORM, PJL_EVIDENCE_FORM, PJL_MAX_ALLOW_YEAR, PJL_MAX_ALLOW_EVENT, PJL_STATUS) VALUES
('UPL', 'Unpaid Leave', 1, 0, 0, null, null, 1);
