Insert into PROJ_DOCUMENT_FOLDER (PDF_CREATED_ON,PDF_NAME,PDF_STATUS,PDF_UPDATED_ON,PDF_CREATED_BY,PDF_PARENT_ID,PDF_EPM_ID,PDF_UPDATED_BY) values 
(null,'Admin',1,null,null,null,null,null);

Insert into PROJ_DOCUMENT_FOLDER (PDF_CREATED_ON,PDF_NAME,PDF_STATUS,PDF_UPDATED_ON,PDF_CREATED_BY,PDF_PARENT_ID,PDF_EPM_ID,PDF_UPDATED_BY) values 
(null,'Client Registration',1,null,null,1,null,null);

Insert into PROJ_DOCUMENT_FOLDER (PDF_CREATED_ON,PDF_NAME,PDF_STATUS,PDF_UPDATED_ON,PDF_CREATED_BY,PDF_PARENT_ID,PDF_EPM_ID,PDF_UPDATED_BY) values 
(null,'Resources',1,null,null,null,null,null);

Insert into PROJ_DOCUMENT_FOLDER (PDF_CREATED_ON,PDF_NAME,PDF_STATUS,PDF_UPDATED_ON,PDF_CREATED_BY,PDF_PARENT_ID,PDF_EPM_ID,PDF_UPDATED_BY) values 
(null,'Employee',1,null,null,3,null,null);

Insert into PROJ_DOCUMENT_FOLDER (PDF_CREATED_ON,PDF_NAME,PDF_STATUS,PDF_UPDATED_ON,PDF_CREATED_BY,PDF_PARENT_ID,PDF_EPM_ID,PDF_UPDATED_BY) values 
(null,'Enrollment/Promotions',1,null,null,4,null,null);

Insert into PROJ_DOCUMENT_FOLDER (PDF_CREATED_ON,PDF_NAME,PDF_STATUS,PDF_UPDATED_ON,PDF_CREATED_BY,PDF_PARENT_ID,PDF_EPM_ID,PDF_UPDATED_BY) values 
(null,'Super Annuation/Provident Fund',1,null,null,4,null,null);

Insert into PROJ_DOCUMENT_FOLDER (PDF_CREATED_ON,PDF_NAME,PDF_STATUS,PDF_UPDATED_ON,PDF_CREATED_BY,PDF_PARENT_ID,PDF_EPM_ID,PDF_UPDATED_BY) values 
(null,'Medical History',1,null,null,4,null,null);

Insert into PROJ_DOCUMENT_FOLDER (PDF_CREATED_ON,PDF_NAME,PDF_STATUS,PDF_UPDATED_ON,PDF_CREATED_BY,PDF_PARENT_ID,PDF_EPM_ID,PDF_UPDATED_BY) values 
(null,'Plant',1,null,null,3,null,null);

Insert into PROJ_DOCUMENT_FOLDER (PDF_CREATED_ON,PDF_NAME,PDF_STATUS,PDF_UPDATED_ON,PDF_CREATED_BY,PDF_PARENT_ID,PDF_EPM_ID,PDF_UPDATED_BY) values 
(null,'Procurement and Delivery Details',1,null,null,8,null,null);

Insert into PROJ_DOCUMENT_FOLDER (PDF_CREATED_ON,PDF_NAME,PDF_STATUS,PDF_UPDATED_ON,PDF_CREATED_BY,PDF_PARENT_ID,PDF_EPM_ID,PDF_UPDATED_BY) values 
(null,'Materials',1,null,null,3,null,null);

Insert into PROJ_DOCUMENT_FOLDER (PDF_CREATED_ON,PDF_NAME,PDF_STATUS,PDF_UPDATED_ON,PDF_CREATED_BY,PDF_PARENT_ID,PDF_EPM_ID,PDF_UPDATED_BY) values 
(null,'Delivery/Supply Details-Record of Delivery Dockets',1,null,null,10,null,null);

Insert into PROJ_DOCUMENT_FOLDER (PDF_CREATED_ON,PDF_NAME,PDF_STATUS,PDF_UPDATED_ON,PDF_CREATED_BY,PDF_PARENT_ID,PDF_EPM_ID,PDF_UPDATED_BY) values 
(null,'Project Dockets-View Dockets',1,null,null,10,null,null);

Insert into PROJ_DOCUMENT_FOLDER (PDF_CREATED_ON,PDF_NAME,PDF_STATUS,PDF_UPDATED_ON,PDF_CREATED_BY,PDF_PARENT_ID,PDF_EPM_ID,PDF_UPDATED_BY) values 
(null,'Fixed Assets',1,null,null,3,null,null);

Insert into PROJ_DOCUMENT_FOLDER (PDF_CREATED_ON,PDF_NAME,PDF_STATUS,PDF_UPDATED_ON,PDF_CREATED_BY,PDF_PARENT_ID,PDF_EPM_ID,PDF_UPDATED_BY) values 
(null,'Purchase/Acquisition',1,null,null,13,null,null);

Insert into PROJ_DOCUMENT_FOLDER (PDF_CREATED_ON,PDF_NAME,PDF_STATUS,PDF_UPDATED_ON,PDF_CREATED_BY,PDF_PARENT_ID,PDF_EPM_ID,PDF_UPDATED_BY) values 
(null,'Asset Sale Records',1,null,null,13,null,null);

Insert into PROJ_DOCUMENT_FOLDER (PDF_CREATED_ON,PDF_NAME,PDF_STATUS,PDF_UPDATED_ON,PDF_CREATED_BY,PDF_PARENT_ID,PDF_EPM_ID,PDF_UPDATED_BY) values 
(null,'Long Term Leasing/Rental History',1,null,null,13,null,null);

Insert into PROJ_DOCUMENT_FOLDER (PDF_CREATED_ON,PDF_NAME,PDF_STATUS,PDF_UPDATED_ON,PDF_CREATED_BY,PDF_PARENT_ID,PDF_EPM_ID,PDF_UPDATED_BY) values 
(null,'Short Term/Casual Occupancy Records and Rental Returns',1,null,null,13,null,null);

Insert into PROJ_DOCUMENT_FOLDER (PDF_CREATED_ON,PDF_NAME,PDF_STATUS,PDF_UPDATED_ON,PDF_CREATED_BY,PDF_PARENT_ID,PDF_EPM_ID,PDF_UPDATED_BY) values 
(null,'Long Term Lease:Rental/Revenue-Actual Revenue',1,null,null,13,null,null);

Insert into PROJ_DOCUMENT_FOLDER (PDF_CREATED_ON,PDF_NAME,PDF_STATUS,PDF_UPDATED_ON,PDF_CREATED_BY,PDF_PARENT_ID,PDF_EPM_ID,PDF_UPDATED_BY) values 
(null,'Car Parking and Toll Collections-Actual Revenue',1,null,null,13,null,null);

Insert into PROJ_DOCUMENT_FOLDER (PDF_CREATED_ON,PDF_NAME,PDF_STATUS,PDF_UPDATED_ON,PDF_CREATED_BY,PDF_PARENT_ID,PDF_EPM_ID,PDF_UPDATED_BY) values 
(null,'Periodical and Schedule maintenance Records',1,null,null,13,null,null);

Insert into PROJ_DOCUMENT_FOLDER (PDF_CREATED_ON,PDF_NAME,PDF_STATUS,PDF_UPDATED_ON,PDF_CREATED_BY,PDF_PARENT_ID,PDF_EPM_ID,PDF_UPDATED_BY) values 
(null,'Repairs and Non Schedule maintenance Records',1,null,null,13,null,null);

Insert into PROJ_DOCUMENT_FOLDER (PDF_CREATED_ON,PDF_NAME,PDF_STATUS,PDF_UPDATED_ON,PDF_CREATED_BY,PDF_PARENT_ID,PDF_EPM_ID,PDF_UPDATED_BY) values 
(null,'Asset Life Status',1,null,null,13,null,null);

Insert into PROJ_DOCUMENT_FOLDER (PDF_CREATED_ON,PDF_NAME,PDF_STATUS,PDF_UPDATED_ON,PDF_CREATED_BY,PDF_PARENT_ID,PDF_EPM_ID,PDF_UPDATED_BY) values 
(null,'Asset Cost and Value Status',1,null,null,13,null,null);

Insert into PROJ_DOCUMENT_FOLDER (PDF_CREATED_ON,PDF_NAME,PDF_STATUS,PDF_UPDATED_ON,PDF_CREATED_BY,PDF_PARENT_ID,PDF_EPM_ID,PDF_UPDATED_BY) values 
(null,'Procurement',1,null,null,null,null,null);

Insert into PROJ_DOCUMENT_FOLDER (PDF_CREATED_ON,PDF_NAME,PDF_STATUS,PDF_UPDATED_ON,PDF_CREATED_BY,PDF_PARENT_ID,PDF_EPM_ID,PDF_UPDATED_BY) values 
(null,'Pre-Contract List',1,null,null,24,null,null);

Insert into PROJ_DOCUMENT_FOLDER (PDF_CREATED_ON,PDF_NAME,PDF_STATUS,PDF_UPDATED_ON,PDF_CREATED_BY,PDF_PARENT_ID,PDF_EPM_ID,PDF_UPDATED_BY) values 
(null,'Reference Documents',1,null,null,25,null,null);

Insert into PROJ_DOCUMENT_FOLDER (PDF_CREATED_ON,PDF_NAME,PDF_STATUS,PDF_UPDATED_ON,PDF_CREATED_BY,PDF_PARENT_ID,PDF_EPM_ID,PDF_UPDATED_BY) values 
(null,'RFQ-Tender Documents',1,null,null,24,null,null);

Insert into PROJ_DOCUMENT_FOLDER (PDF_CREATED_ON,PDF_NAME,PDF_STATUS,PDF_UPDATED_ON,PDF_CREATED_BY,PDF_PARENT_ID,PDF_EPM_ID,PDF_UPDATED_BY) values 
(null,'Upload/View File',1,null,null,27,null,null);

Insert into PROJ_DOCUMENT_FOLDER (PDF_CREATED_ON,PDF_NAME,PDF_STATUS,PDF_UPDATED_ON,PDF_CREATED_BY,PDF_PARENT_ID,PDF_EPM_ID,PDF_UPDATED_BY) values 
(null,'Generate Single PO/Multiple PO',1,null,null,24,null,null);

Insert into PROJ_DOCUMENT_FOLDER (PDF_CREATED_ON,PDF_NAME,PDF_STATUS,PDF_UPDATED_ON,PDF_CREATED_BY,PDF_PARENT_ID,PDF_EPM_ID,PDF_UPDATED_BY) values 
(null,'Appendices-Add-Upload File',1,null,null,29,null,null);

Insert into PROJ_DOCUMENT_FOLDER (PDF_CREATED_ON,PDF_NAME,PDF_STATUS,PDF_UPDATED_ON,PDF_CREATED_BY,PDF_PARENT_ID,PDF_EPM_ID,PDF_UPDATED_BY) values 
(null,'Other Documents',1,null,null,null,null,null);