
INSERT INTO resource_curves (RC_CRM_ID,RC_TYPE,RC_CATG,RC_RANGE1,RC_RANGE2,RC_RANGE3,RC_RANGE4,RC_RANGE5,RC_RANGE6,RC_RANGE7,RC_RANGE8,RC_RANGE9,RC_RANGE10,RC_TOTAL,RC_STATUS,RC_CREATED_BY,RC_CREATED_ON,RC_UPDATED_BY,RC_UPDATED_ON,RC_DEFAULT) VALUES (NULL,'FRONTLOADED','Global',13,13,13,13,13,7,7,7,7,7,100.00,1,NULL,NULL,NULL,NULL,1);

INSERT INTO resource_curves (RC_CRM_ID,RC_TYPE,RC_CATG,RC_RANGE1,RC_RANGE2,RC_RANGE3,RC_RANGE4,RC_RANGE5,RC_RANGE6,RC_RANGE7,RC_RANGE8,RC_RANGE9,RC_RANGE10,RC_TOTAL,RC_STATUS,RC_CREATED_BY,RC_CREATED_ON,RC_UPDATED_BY,RC_UPDATED_ON,RC_DEFAULT) VALUES (NULL,'BACKLOADED','Global',7,7,7,7,7,13,13,13,13,13,100.00,1,NULL,NULL,NULL,NULL,1);

INSERT INTO resource_curves (RC_CRM_ID,RC_TYPE,RC_CATG,RC_RANGE1,RC_RANGE2,RC_RANGE3,RC_RANGE4,RC_RANGE5,RC_RANGE6,RC_RANGE7,RC_RANGE8,RC_RANGE9,RC_RANGE10,RC_TOTAL,RC_STATUS,RC_CREATED_BY,RC_CREATED_ON,RC_UPDATED_BY,RC_UPDATED_ON,RC_DEFAULT) VALUES (NULL,'BELLSHEPED','Global',1,1,8,15,23,23,15,8,3,1,100.00,1,NULL,NULL,NULL,NULL,1);

INSERT INTO resource_curves (RC_CRM_ID,RC_TYPE,RC_CATG,RC_RANGE1,RC_RANGE2,RC_RANGE3,RC_RANGE4,RC_RANGE5,RC_RANGE6,RC_RANGE7,RC_RANGE8,RC_RANGE9,RC_RANGE10,RC_TOTAL,RC_STATUS,RC_CREATED_BY,RC_CREATED_ON,RC_UPDATED_BY,RC_UPDATED_ON,RC_DEFAULT) VALUES (NULL,'DOUBLEPEAK','Global',5,10,10,5,5,10,20,20,10,5,100.00,1,NULL,NULL,NULL,NULL,1);

INSERT INTO resource_curves (RC_CRM_ID,RC_TYPE,RC_CATG,RC_RANGE1,RC_RANGE2,RC_RANGE3,RC_RANGE4,RC_RANGE5,RC_RANGE6,RC_RANGE7,RC_RANGE8,RC_RANGE9,RC_RANGE10,RC_TOTAL,RC_STATUS,RC_CREATED_BY,RC_CREATED_ON,RC_UPDATED_BY,RC_UPDATED_ON,RC_DEFAULT) VALUES (NULL,'EARLYPEAK','Global',5,10,20,20,15,10,10,5,3,2,100.00,1,NULL,NULL,NULL,NULL,1);

INSERT INTO resource_curves (RC_CRM_ID,RC_TYPE,RC_CATG,RC_RANGE1,RC_RANGE2,RC_RANGE3,RC_RANGE4,RC_RANGE5,RC_RANGE6,RC_RANGE7,RC_RANGE8,RC_RANGE9,RC_RANGE10,RC_TOTAL,RC_STATUS,RC_CREATED_BY,RC_CREATED_ON,RC_UPDATED_BY,RC_UPDATED_ON,RC_DEFAULT) VALUES (NULL,'OFFSETTRIANGULAR','Global',2,5,7,10,13,15,17,14,10,7,100.00,1,NULL,NULL,NULL,NULL,1);

INSERT INTO resource_curves (RC_CRM_ID,RC_TYPE,RC_CATG,RC_RANGE1,RC_RANGE2,RC_RANGE3,RC_RANGE4,RC_RANGE5,RC_RANGE6,RC_RANGE7,RC_RANGE8,RC_RANGE9,RC_RANGE10,RC_TOTAL,RC_STATUS,RC_CREATED_BY,RC_CREATED_ON,RC_UPDATED_BY,RC_UPDATED_ON,RC_DEFAULT) VALUES (NULL,'THREE STEP','Global',8,8,8,13,13,13,13,8,8,8,100.00,1,NULL,NULL,NULL,NULL,1);

INSERT INTO resource_curves (RC_CRM_ID,RC_TYPE,RC_CATG,RC_RANGE1,RC_RANGE2,RC_RANGE3,RC_RANGE4,RC_RANGE5,RC_RANGE6,RC_RANGE7,RC_RANGE8,RC_RANGE9,RC_RANGE10,RC_TOTAL,RC_STATUS,RC_CREATED_BY,RC_CREATED_ON,RC_UPDATED_BY,RC_UPDATED_ON,RC_DEFAULT) VALUES (NULL,'TRAPEZOIDAL DECREASE','Global',18,17,14,13,11,9,7,6,3,2,100.00,1,NULL,NULL,NULL,NULL,1);

INSERT INTO resource_curves (RC_CRM_ID,RC_TYPE,RC_CATG,RC_RANGE1,RC_RANGE2,RC_RANGE3,RC_RANGE4,RC_RANGE5,RC_RANGE6,RC_RANGE7,RC_RANGE8,RC_RANGE9,RC_RANGE10,RC_TOTAL,RC_STATUS,RC_CREATED_BY,RC_CREATED_ON,RC_UPDATED_BY,RC_UPDATED_ON,RC_DEFAULT) VALUES (NULL,'TRIANGULAR','Global',2,6,10,14,18,18,14,10,6,2,100.00,1,NULL,NULL,NULL,NULL,1);

INSERT INTO resource_curves (RC_CRM_ID,RC_TYPE,RC_CATG,RC_RANGE1,RC_RANGE2,RC_RANGE3,RC_RANGE4,RC_RANGE5,RC_RANGE6,RC_RANGE7,RC_RANGE8,RC_RANGE9,RC_RANGE10,RC_TOTAL,RC_STATUS,RC_CREATED_BY,RC_CREATED_ON,RC_UPDATED_BY,RC_UPDATED_ON,RC_DEFAULT) VALUES (NULL,'TRIANGULAR INCREASE','Global',2,3,6,7,9,11,13,14,17,18,100.00,1,NULL,NULL,NULL,NULL,1);