

INSERT INTO role_mstr
(
RLM_NAME,
RLM_CRM_ID,
RLM_STATUS,
RLM_CREATED_BY,
RLM_CREATED_ON,
RLM_UPDATED_BY,
RLM_UPDATED_ON,
RLM_DEFAULT)
VALUES
('ADMIN',1,1,NULL,NULL,NULL,to_timestamp('2018-05-23 17:41:47', 'YYYY-MM-DD HH24:MI:SS'),NULL);
INSERT INTO role_mstr
(
RLM_NAME,
RLM_CRM_ID,
RLM_STATUS,
RLM_CREATED_BY,
RLM_CREATED_ON,
RLM_UPDATED_BY,
RLM_UPDATED_ON,
RLM_DEFAULT)
VALUES
('ProjectManager',NULL,1,NULL,NULL,NULL,NULL,NULL);
INSERT INTO role_mstr
(
RLM_NAME,
RLM_CRM_ID,
RLM_STATUS,
RLM_CREATED_BY,
RLM_CREATED_ON,
RLM_UPDATED_BY,
RLM_UPDATED_ON,
RLM_DEFAULT)
VALUES
('HighLevelUser',NULL,1,NULL,NULL,NULL,NULL,NULL);
INSERT INTO role_mstr
(
RLM_NAME,
RLM_CRM_ID,
RLM_STATUS,
RLM_CREATED_BY,
RLM_CREATED_ON,
RLM_UPDATED_BY,
RLM_UPDATED_ON,
RLM_DEFAULT)
VALUES
('MiddleLevelUser',NULL,1,NULL,NULL,NULL,NULL,NULL);
INSERT INTO role_mstr
(
RLM_NAME,
RLM_CRM_ID,
RLM_STATUS,
RLM_CREATED_BY,
RLM_CREATED_ON,
RLM_UPDATED_BY,
RLM_UPDATED_ON,
RLM_DEFAULT)
VALUES
('LowlevelUser',NULL,1,NULL,NULL,NULL,NULL,1);
INSERT INTO role_mstr
(
RLM_NAME,
RLM_CRM_ID,
RLM_STATUS,
RLM_CREATED_BY,
RLM_CREATED_ON,
RLM_UPDATED_BY,
RLM_UPDATED_ON,
RLM_DEFAULT)
VALUES
('IT-ADMIN',NULL,1,NULL,NULL,NULL,NULL,NULL);
